### ISSUE TITLE
Support for sep= line

### ISSUE THREAD

**Issue by wvdvegt** [tspence/csharp-csv-reader#28]
Hi

I'm missing some support for dynamically setting the separator if in the first line of the csv:

`sep=;`

is specified (or sep=, for comma as separator).

**Comment by wvdvegt** [comment]
Below the functionality i'm looking for:

```
StreamReader sr = File.OpenText(Path.Combine(basePath, "data.csv"));

CSVSettings cs = new CSVSettings();

// Determine the separator. If not specified re-open the stream.
String sep = sr.ReadLine();
if (sep.StartsWith("sep=", StringComparison.InvariantCultureIgnoreCase))
{
  cs.FieldDelimiter = sep.Last();
}
else
{
  sr.Close();
  sr = File.OpenText(Path.Combine(basePath, "data.csv"));
}

// Process the remaining csv including a header if present.
using (CSVReader cr = new CSVReader(sr, cs))
{
  // Process
}
```

**Comment by tspence** [comment]
Interesting!  This isn't a behavior I've seen before.  Does this format support spaces, like `sep = |`, or alternative spellings like `separator = |`?

**Comment by wvdvegt** [comment]
Hi


It's just sep= followed by the separator. Excel supports it and it makes life easier importing csv. When using \t for tab it must be quoted. So my code is not enough to cover this feature with sll values.


See for example: https://blog.tjitjing.com/index.php/2016/07/set-separator-delimiter-in-csv-file-to-open-correctly-in-excel.html
Wim van der VegtFrom: Ted Spence ***@***.***>Sent: Monday, 3 January 2022, 18:07To: tspence/csharp-csv-readerCc: wvdvegt; AuthorSubject: Re: [tspence/csharp-csv-reader] Support for sep= line (Issue #28)
Interesting!  This isn't a behavior I've seen before.  Does this format support spaces, like sep = |, or alternative spellings like separator = |?

**Comment by tspence** [comment]
This is a really interesting feature which I surprisingly had not encountered in the entire time I worked with CSV files!  I would love to add this to the standard.  I will research this and add support for it.  I am going to keep researching - do you want to submit a pull request or wait until I come up with an answer?

**Comment by wvdvegt** [comment]
Hi,


I'll probably wait for an update (got a workaround) as i keep struggling with the mechanics around pull requests.
Wim van der Vegt

**Comment by tspence** [comment]
More documentation: 

https://superuser.com/questions/773644/what-is-the-sep-metadata-you-can-add-to-csvs
https://www.rfc-editor.org/rfc/rfc4180

Apparently this feature is excel specific, but since Excel is one of the most common ways to handle CSV files, this makes sense to support.

**Comment by tspence** [comment]
Quick update: I'm working on this refactoring.  I've been able to find enough information about it to be somewhat confident that I can handle it correctly.

**Comment by tspence** [comment]
Okay, looks like PR#37 adds this feature.  Here's how it works:
* You can specify in the CSV Settings object "AllowSepLine=true".
* If you specify this flag, the first line of the file will be checked for sep line status.
* If the line begins with "sep=", it will consume the next non-whitespace character.
* The sep line will also permit spaces after sep but before the equals sign.

Would love to hear whether this solves your use case!

**Comment by tspence** [comment]
Marking as closed.  If anything else comes up please feel free to re-open.
