### ISSUE TITLE
Quoting of text 

### ISSUE THREAD

**Issue by wvdvegt** [tspence/csharp-csv-reader#29]
Is it possible to add an option to force quote around all text (except numeric values, so basically all that passes Double.TryConvert() without quotes).

I noticed that this lib either enquotes minimal (so only fields with line ends or field separators in it, which is ok) or everything (inlcuding numeric values). The option i would like to see is in between, quote all textual fields.

**Comment by tspence** [comment]
Addressed in version 3.1.0
