### ISSUE TITLE
in CSV.cs, function ChopFile() cw.Dispose() called on Null cw

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tspence/csharp-csv-reader#3]
```
When calling Dispose on cw, check first is not Null.
```

Original issue reported on code.google.com by `jp.eugs...@gmail.com` on 16 Apr 2013 at 11:12

**Comment by tspence** [comment]
Apparently the fix for tihs never got committed - sorry about that!  Fixed for version 1.2.
