### ISSUE TITLE
CSV files which have an empty System.Single field as the last column fail to deserialize

### ISSUE THREAD

**Issue by AshwinGanesan** [tspence/csharp-csv-reader#38]
CSV files which have empty fields meant to be deserialized to `System.Single` in their last column fail to deserialize:

![image](https://user-images.githubusercontent.com/52789945/159589628-054844cc-9633-49a8-983e-e644f17cd765.png)

**Comment by tspence** [comment]
Looks like this specifically affects the DeserializeAsync code path.  I will have to see if I can find a way to merge the code between these two functions so there's less risk of code divergence.

**Comment by AshwinGanesan** [comment]
Makes sense!

**Comment by tspence** [comment]
Addressed in 3.0.9
