### ISSUE TITLE
What options are supported by this DLL?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tspence/csharp-csv-reader#4]
```
Does it handles Double Quotes, Single Quotes, and a column having large amount 
of text which contains commas? 
```

Original issue reported on code.google.com by `babji.su...@gmail.com` on 16 Oct 2013 at 5:10

**Comment by tspence** [comment]
Yes, this program supports all different options.  You will need to specify both the "field delimiter" - usually a comma or a tab character - and a "text qualifier" - usually double quotes.  The combination of those two values allows all sorts of embedded information.

Note that some CSV files include multi-line comments.  This means it is not possible to parse some files using File.ReadAllLines() - in that case, please make sure you use the CSVReader object and allow it to stream values back to you.
