### ISSUE TITLE
Check prior to SetValue  - PropertyInfo.CanWrite on deserialize

### ISSUE THREAD

**Issue by MicroTrendsTom** [tspence/csharp-csv-reader#44]
usage example
List<TradeViewPointRow> tradeViewPoint = CSVFile.CSV.Deserialize<TradeViewPointRow>(cSV, cSVSettings).ToList();

note the CSV contains some readonly output which arrived there due to other layers/services requiring the data point  - created by a Property Get derived from other columns etc.

Avoid an exception " unable to find Property Set etc" and ignore the property
public class CSVReader : IEnumerable<string[]>, IDisposable
{

 public T Deserialize<T>(string[] line, int row_num, CSVSettings settings) where T : class, new()
{
                     ...
                     if (Properties[i] != null)
                    {
                        Properties[i].SetValue(obj, value, null);
                    }
                   else...
}

add inline check for CanWrite

public T Deserialize<T>(string[] line, int row_num, CSVSettings settings) where T : class, new()
{
                     ...
                      if (Properties[i] != null && Properties[i].CanWrite)
                    {
                        Properties[i].SetValue(obj, value, null);
                    }
                   else...
}

}

**Comment by MicroTrendsTom** [comment]
by the way excellent work i was in dependency hell with CSVHelper and found this and has saved me an eon of time thank you so much

**Comment by tspence** [comment]
Awesome find, thank you very much! Let me put in a test for that
