### ISSUE TITLE
Enhancement    -  CSVSettings.ColumnsToExclude

### ISSUE THREAD

**Issue by MicroTrendsTom** [tspence/csharp-csv-reader#45]
just an idea maybe a new issue/enhancement - 
if we specify in CSVSettings.ColumnsToExclude....   as List<string> 
so in fact we could skip some readonly or surplus properties/fields and simply pass that in etc

**Comment by tspence** [comment]
Solid idea!

**Comment by tspence** [comment]
Addressed in version 3.1.0
