### ISSUE TITLE
Preserving new lines in text fields?

### ISSUE THREAD

**Issue by domdere** [tspence/csharp-csv-reader#59]
Hi, I just recently updated CSVFile from a fairly old version, and previously when it parsed a text field with multiple consecutive empty lines, those empty lines used to come through in the deserialised output but now only 1 newline comes through.

for instance "blah\r\n\r\n\r\nfoo" in a csv file will result in "blah\r\nfoo" in the parsed output.

It this intentional and is there an option to get the old behaviour back?

**Comment by tspence** [comment]
Interesting!  Thanks for reporting this.  Let me write a test case for this scenario and we'll see if this needs a patch.

**Comment by domdere** [comment]
Ah cool thanks for taking a look :)

**Comment by tspence** [comment]
@domdere I have a pull request that demonstrates the problem and implements a fix.  Let me add a few more tests and I can release this as 3.1.2.

**Comment by domdere** [comment]
Oh, great, thank you very much!

**Comment by tspence** [comment]
Would you be able to try 3.1.2 and let me know if this fixes your issue?

**Comment by domdere** [comment]
Sorry I took so long, I gave it a try and it appears to work, thanks a lot!
